/**
 * Seed script — Copa do Mundo (futebol de campo)
 *
 * Pré-requisito: baixar a chave de serviço do Firebase Console
 *   Configurações do projeto → Contas de serviço → Gerar nova chave privada
 *   Salvar como: scripts/service-account.json
 *
 * Uso: node scripts/seed-copa.js
 */

import { createRequire } from 'module';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const require   = createRequire(import.meta.url);
const admin     = require('firebase-admin');
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const serviceAccount = JSON.parse(
  readFileSync(path.join(__dirname, 'service-account.json'), 'utf8')
);

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

// ── Dados dos times ──────────────────────────────────────────────
// posições: GK | ZAG | LAT | MCM | ATA
const TIMES = [
  {
    name: 'Brasil', shieldEmoji: '🇧🇷',
    players: [
      { name: 'Alisson',           position: 'GK'  },
      { name: 'Ederson',           position: 'GK'  },
      { name: 'Weverton',          position: 'GK'  },
      { name: 'Wesley',            position: 'LAT' },
      { name: 'Douglas Santos',    position: 'LAT' },
      { name: 'Alex Sandro',       position: 'LAT' },
      { name: 'Gabriel Magalhães', position: 'ZAG' },
      { name: 'Marquinhos',        position: 'ZAG' },
      { name: 'Danilo',            position: 'ZAG' },
      { name: 'Bremer',            position: 'ZAG' },
      { name: 'Ibañez',            position: 'ZAG' },
      { name: 'Léo Pereira',       position: 'ZAG' },
      { name: 'Bruno Guimarães',   position: 'MCM' },
      { name: 'Casemiro',          position: 'MCM' },
      { name: 'Danilo Santos',     position: 'MCM' },
      { name: 'Fabinho',           position: 'MCM' },
      { name: 'Lucas Paquetá',     position: 'MCM' },
      { name: 'Neymar',            position: 'ATA' },
      { name: 'Raphinha',          position: 'ATA' },
      { name: 'Vinicius Junior',   position: 'ATA' },
      { name: 'Luiz Henrique',     position: 'ATA' },
      { name: 'Matheus Cunha',     position: 'ATA' },
      { name: 'Gabriel Martinelli',position: 'ATA' },
      { name: 'Igor Thiago',       position: 'ATA' },
      { name: 'Endrick',           position: 'ATA' },
      { name: 'Rayan',             position: 'ATA' },
    ],
  },
  {
    name: 'Portugal', shieldEmoji: '🇵🇹',
    players: [
      { name: 'Diogo Costa',          position: 'GK'  },
      { name: 'José Sá',              position: 'GK'  },
      { name: 'Rui Silva',            position: 'GK'  },
      { name: 'Ricardo Velho',        position: 'GK'  },
      { name: 'Diogo Dalot',          position: 'LAT' },
      { name: 'Matheus Nunes',        position: 'LAT' },
      { name: 'Nélson Semedo',        position: 'LAT' },
      { name: 'João Cancelo',         position: 'LAT' },
      { name: 'Nuno Mendes',          position: 'LAT' },
      { name: 'Gonçalo Inácio',       position: 'ZAG' },
      { name: 'Renato Veiga',         position: 'ZAG' },
      { name: 'Rúben Dias',           position: 'ZAG' },
      { name: 'Tomás Araújo',         position: 'ZAG' },
      { name: 'Rúben Neves',          position: 'MCM' },
      { name: 'Samuel Costa',         position: 'MCM' },
      { name: 'João Neves',           position: 'MCM' },
      { name: 'Vitinha',              position: 'MCM' },
      { name: 'Bruno Fernandes',      position: 'MCM' },
      { name: 'Bernardo Silva',       position: 'MCM' },
      { name: 'João Félix',           position: 'ATA' },
      { name: 'Trincão',              position: 'ATA' },
      { name: 'Francisco Conceição',  position: 'ATA' },
      { name: 'Pedro Neto',           position: 'ATA' },
      { name: 'Rafael Leão',          position: 'ATA' },
      { name: 'Gonçalo Guedes',       position: 'ATA' },
      { name: 'Gonçalo Ramos',        position: 'ATA' },
      { name: 'Cristiano Ronaldo',    position: 'ATA' },
    ],
  },
  {
    name: 'Bósnia e Herzegovina', shieldEmoji: '🇧🇦',
    players: [
      { name: 'Nikola Vasilj',          position: 'GK'  },
      { name: 'Martin Zlomislic',        position: 'GK'  },
      { name: 'Osman Hadzikic',          position: 'GK'  },
      { name: 'Amar Dedic',              position: 'LAT' },
      { name: 'Sead Kolasinac',          position: 'LAT' },
      { name: 'Nidal Celik',             position: 'ZAG' },
      { name: 'Dennis Hadzikadunic',     position: 'ZAG' },
      { name: 'Nihad Mujakic',           position: 'ZAG' },
      { name: 'Nikola Katic',            position: 'ZAG' },
      { name: 'Tarik Muharemovic',       position: 'ZAG' },
      { name: 'Stjepan Radeljic',        position: 'ZAG' },
      { name: 'Benjamin Tahirovic',      position: 'MCM' },
      { name: 'Amir Hadziahmetovic',     position: 'MCM' },
      { name: 'Ivan Sunjic',             position: 'MCM' },
      { name: 'Ermin Mahmic',            position: 'MCM' },
      { name: 'Ivan Basic',              position: 'MCM' },
      { name: 'Armin Gigovic',           position: 'MCM' },
      { name: 'Dzenis Burnic',           position: 'MCM' },
      { name: 'Esmir Bajraktarevic',     position: 'MCM' },
      { name: 'Ermedin Demirovic',       position: 'ATA' },
      { name: 'Amar Memic',              position: 'ATA' },
      { name: 'Kerim Alajbegovic',       position: 'ATA' },
      { name: 'Jovo Lukic',              position: 'ATA' },
      { name: 'Samed Bazdar',            position: 'ATA' },
      { name: 'Haris Tabakovic',         position: 'ATA' },
      { name: 'Edin Dzeko',              position: 'ATA' },
    ],
  },
  {
    name: 'Suécia', shieldEmoji: '🇸🇪',
    players: [
      { name: 'Viktor Johansson',      position: 'GK'  },
      { name: 'Kristoffer Nordfeldt',  position: 'GK'  },
      { name: 'Jacob Zetterström',     position: 'GK'  },
      { name: 'Gabriel Gudmundsson',   position: 'LAT' },
      { name: 'Emil Holm',             position: 'LAT' },
      { name: 'Daniel Svensson',       position: 'LAT' },
      { name: 'Elliot Stroud',         position: 'LAT' },
      { name: 'Carl Starfelt',         position: 'ZAG' },
      { name: 'Victor Lindelöf',       position: 'ZAG' },
      { name: 'Gustaf Lagerbielke',    position: 'ZAG' },
      { name: 'Hjalmar Ekdal',         position: 'ZAG' },
      { name: 'Eric Smith',            position: 'ZAG' },
      { name: 'Isak Hien',             position: 'ZAG' },
      { name: 'Lucas Bergvall',        position: 'MCM' },
      { name: 'Mattias Svanberg',      position: 'MCM' },
      { name: 'Besfort Zenelie',       position: 'MCM' },
      { name: 'Jesper Karlstrom',      position: 'MCM' },
      { name: 'Yasin Ayari',           position: 'MCM' },
      { name: 'Alexander Isak',        position: 'ATA' },
      { name: 'Viktor Gyökeres',       position: 'ATA' },
      { name: 'Anthony Elanga',        position: 'ATA' },
      { name: 'Taha Ali',              position: 'ATA' },
      { name: 'Alexander Bernhardsson',position: 'ATA' },
      { name: 'Benjamin Nygren',       position: 'ATA' },
      { name: 'Ken Sema',              position: 'ATA' },
      { name: 'Gustaf Nilsson',        position: 'ATA' },
    ],
  },
  {
    name: 'Nova Zelândia', shieldEmoji: '🇳🇿',
    players: [
      { name: 'Max Crocombe',     position: 'GK'  },
      { name: 'Alex Paulsen',     position: 'GK'  },
      { name: 'Michael Woud',     position: 'GK'  },
      { name: 'Tim Payne',        position: 'LAT' },
      { name: 'Callan Elliot',    position: 'LAT' },
      { name: 'Liberato Cacace',  position: 'LAT' },
      { name: 'Francis de Vries', position: 'LAT' },
      { name: 'Nando Pijnaker',   position: 'ZAG' },
      { name: 'Tyler Bindon',     position: 'ZAG' },
      { name: 'Finn Surman',      position: 'ZAG' },
      { name: 'Michael Boxall',   position: 'ZAG' },
      { name: 'Tommy Smith',      position: 'ZAG' },
      { name: 'Ryan Thomas',      position: 'MCM' },
      { name: 'Marko Stamenić',   position: 'MCM' },
      { name: 'Alex Rufer',       position: 'MCM' },
      { name: 'Lachlan Bayliss',  position: 'MCM' },
      { name: 'Matt Garbett',     position: 'MCM' },
      { name: 'Callum McCowatt',  position: 'MCM' },
      { name: 'Sarpreet Singh',   position: 'MCM' },
      { name: 'Eli Just',         position: 'ATA' },
      { name: 'Ben Old',          position: 'ATA' },
      { name: 'Kosta Barbarouses',position: 'ATA' },
      { name: 'Jesse Randall',    position: 'ATA' },
      { name: 'Ben Waine',        position: 'ATA' },
      { name: 'Chris Wood',       position: 'ATA' },
    ],
  },
  {
    name: 'França', shieldEmoji: '🇫🇷',
    players: [
      { name: 'Mike Maignan',          position: 'GK'  },
      { name: 'Robin Risser',          position: 'GK'  },
      { name: 'Brice Samba',           position: 'GK'  },
      { name: 'Lucas Digne',           position: 'LAT' },
      { name: 'Jules Koundé',          position: 'LAT' },
      { name: 'Malo Gusto',            position: 'LAT' },
      { name: 'Theo Hernandez',        position: 'LAT' },
      { name: 'Lucas Hernandez',       position: 'ZAG' },
      { name: 'Ibrahima Konaté',       position: 'ZAG' },
      { name: 'William Saliba',        position: 'ZAG' },
      { name: 'Dayot Upamecano',       position: 'ZAG' },
      { name: 'Maxence Lacroix',       position: 'ZAG' },
      { name: 'Adrien Rabiot',         position: 'MCM' },
      { name: 'Warren Zaïre-Emery',    position: 'MCM' },
      { name: "N'Golo Kanté",          position: 'MCM' },
      { name: 'Manu Koné',             position: 'MCM' },
      { name: 'Aurélien Tchouaméni',   position: 'MCM' },
      { name: 'Michael Olise',         position: 'MCM' },
      { name: 'Rayan Cherki',          position: 'MCM' },
      { name: 'Maghnès Akliouche',     position: 'ATA' },
      { name: 'Bradley Barcola',       position: 'ATA' },
      { name: 'Ousmane Dembélé',       position: 'ATA' },
      { name: 'Désiré Doué',           position: 'ATA' },
      { name: 'Kylian Mbappé',         position: 'ATA' },
      { name: 'Marcus Thuram',         position: 'ATA' },
      { name: 'Jean-Philippe Mateta',  position: 'ATA' },
    ],
  },
  {
    name: 'Bélgica', shieldEmoji: '🇧🇪',
    players: [
      { name: 'Courtois',              position: 'GK'  },
      { name: 'Lammens',               position: 'GK'  },
      { name: 'Mike Penders',          position: 'GK'  },
      { name: 'Joaquin Seys',          position: 'LAT' },
      { name: 'Maxim De Cuyper',       position: 'LAT' },
      { name: 'Thomas Meunier',        position: 'LAT' },
      { name: 'Timothy Castagne',      position: 'LAT' },
      { name: 'Arthur Theate',         position: 'ZAG' },
      { name: 'Zeno Debast',           position: 'ZAG' },
      { name: 'Koni De Winter',        position: 'ZAG' },
      { name: 'Brandon Mechele',       position: 'ZAG' },
      { name: 'Nathan Ngoy',           position: 'ZAG' },
      { name: 'Amadou Onana',          position: 'MCM' },
      { name: 'Nicolas Raskin',        position: 'MCM' },
      { name: 'Youri Tielemans',       position: 'MCM' },
      { name: 'Axel Witsel',           position: 'MCM' },
      { name: 'Kevin De Bruyne',       position: 'MCM' },
      { name: 'Charles De Ketelaere',  position: 'MCM' },
      { name: 'Hans Vanaken',          position: 'MCM' },
      { name: 'Mathias Fernandez-Pardo',position: 'ATA'},
      { name: 'Jeremy Doku',           position: 'ATA' },
      { name: 'Romelu Lukaku',         position: 'ATA' },
      { name: 'Alexis Saelemaekers',   position: 'ATA' },
      { name: 'Leandro Trossard',      position: 'ATA' },
      { name: 'Dodi Lukebakio',        position: 'ATA' },
      { name: 'Diego Moreira',         position: 'ATA' },
    ],
  },
  {
    name: 'Japão', shieldEmoji: '🇯🇵',
    players: [
      { name: 'Zion Suzuki',       position: 'GK'  },
      { name: 'Keisuke Osako',     position: 'GK'  },
      { name: 'Tomoki Hayakawa',   position: 'GK'  },
      { name: 'Takehiro Tomiyasu', position: 'LAT' },
      { name: 'Yukinari Sugawara', position: 'LAT' },
      { name: 'Yuto Nagatomo',     position: 'LAT' },
      { name: 'Ko Itakura',        position: 'ZAG' },
      { name: 'Tsuyoshi Watanabe', position: 'ZAG' },
      { name: 'Shogo Taniguchi',   position: 'ZAG' },
      { name: 'Hiroki Ito',        position: 'ZAG' },
      { name: 'Junnosuke Suzuki',  position: 'ZAG' },
      { name: 'Wataru Endo',       position: 'MCM' },
      { name: 'Ayumu Seko',        position: 'MCM' },
      { name: 'Ao Tanaka',         position: 'MCM' },
      { name: 'Kaishu Sano',       position: 'MCM' },
      { name: 'Ritsu Doan',        position: 'MCM' },
      { name: 'Daizen Maeda',      position: 'MCM' },
      { name: 'Daichi Kamada',     position: 'MCM' },
      { name: 'Keito Nakamura',    position: 'MCM' },
      { name: 'Takefusa Kubo',     position: 'ATA' },
      { name: 'Kento Shiogai',     position: 'ATA' },
      { name: 'Yuito Suzuki',      position: 'ATA' },
      { name: 'Junya Ito',         position: 'ATA' },
      { name: 'Ayase Ueda',        position: 'ATA' },
      { name: 'Koki Ogawa',        position: 'ATA' },
      { name: 'Keisuke Goto',      position: 'ATA' },
    ],
  },
  {
    name: "Côte d'Ivoire", shieldEmoji: '🇨🇮',
    players: [
      { name: 'Yahia Fofana',       position: 'GK'  },
      { name: 'Mohamed Koné',       position: 'GK'  },
      { name: 'Alban Lafont',       position: 'GK'  },
      { name: 'Guéla Doué',         position: 'LAT' },
      { name: 'Ghislain Konan',     position: 'LAT' },
      { name: 'Evan Ndicka',        position: 'ZAG' },
      { name: 'Odilon Kossounou',   position: 'ZAG' },
      { name: 'Emmanuel Agbadou',   position: 'ZAG' },
      { name: 'Clément Akpa',       position: 'ZAG' },
      { name: 'Ousmane Diomande',   position: 'ZAG' },
      { name: 'Wilfried Singo',     position: 'ZAG' },
      { name: 'Franck Kessié',      position: 'MCM' },
      { name: 'Seko Fofana',        position: 'MCM' },
      { name: 'Christ Inao Oulaï',  position: 'MCM' },
      { name: 'Jean Michaël Seri',  position: 'MCM' },
      { name: 'Ibrahim Sangaré',    position: 'MCM' },
      { name: 'Simon Adingra',      position: 'ATA' },
      { name: 'Ange-Yoan Bonny',    position: 'ATA' },
      { name: 'Amad Diallo',        position: 'ATA' },
      { name: 'Oumar Diakité',      position: 'ATA' },
      { name: 'Yan Diomande',       position: 'ATA' },
      { name: 'Evann Guessand',     position: 'ATA' },
      { name: 'Nicolas Pépé',       position: 'ATA' },
      { name: 'Bazoumana Touré',    position: 'ATA' },
      { name: 'Elye Wahi',          position: 'ATA' },
      { name: 'Parfait Guiagon',    position: 'ATA' },
    ],
  },
  {
    name: 'Tunísia', shieldEmoji: '🇹🇳',
    players: [
      { name: 'Aymen Dahmen',          position: 'GK'  },
      { name: 'Sabri Ben Hassen',      position: 'GK'  },
      { name: 'Abdelmouhib Chamakh',   position: 'GK'  },
      { name: 'Ali Abdi',              position: 'LAT' },
      { name: 'Yan Valéry',            position: 'LAT' },
      { name: 'Moutaz Neffati',        position: 'LAT' },
      { name: 'Ben Hmida',             position: 'LAT' },
      { name: 'Omar Rekik',            position: 'ZAG' },
      { name: 'Montassar Talbi',       position: 'ZAG' },
      { name: 'Dylan Bronn',           position: 'ZAG' },
      { name: 'Raed Chikhaoui',        position: 'ZAG' },
      { name: 'Adem Arous',            position: 'ZAG' },
      { name: 'Ellyes Skhiri',         position: 'MCM' },
      { name: 'Anis Ben Slimane',      position: 'MCM' },
      { name: 'Rani Khedira',          position: 'MCM' },
      { name: 'Mohamed Hadj-Mahmoud',  position: 'MCM' },
      { name: 'Mortadha Ben Ouanes',   position: 'MCM' },
      { name: 'Hannbial',              position: 'MCM' },
      { name: 'Ismaël Gharbi',         position: 'MCM' },
      { name: 'Elias Saäd',            position: 'ATA' },
      { name: 'Khalil Ayari',          position: 'ATA' },
      { name: 'Elias Achouri',         position: 'ATA' },
      { name: 'Sebastian Tounekti',    position: 'ATA' },
      { name: 'Hazem Mastouri',        position: 'ATA' },
      { name: 'Firas Chawat',          position: 'ATA' },
      { name: 'Rayan Elloumi',         position: 'ATA' },
    ],
  },
  {
    name: 'Haiti', shieldEmoji: '🇭🇹',
    players: [
      { name: 'Johnny Placide',       position: 'GK'  },
      { name: 'Alexandre Pierre',     position: 'GK'  },
      { name: 'Josué Duverger',       position: 'GK'  },
      { name: 'Carlens Arcus',        position: 'LAT' },
      { name: 'Wilguens Pauguain',    position: 'LAT' },
      { name: 'Duke Lacroix',         position: 'LAT' },
      { name: 'Martin Experience',    position: 'LAT' },
      { name: 'Keeto Thermoncy',      position: 'ZAG' },
      { name: 'JK Duverne',           position: 'ZAG' },
      { name: 'Ricardo Ade',          position: 'ZAG' },
      { name: 'Hannes Delcroix',      position: 'ZAG' },
      { name: 'Leverton Pierre',      position: 'MCM' },
      { name: 'Carl-Fred Sainthe',    position: 'MCM' },
      { name: 'Dominique Simon',      position: 'MCM' },
      { name: 'Jean-Jacques Danley',  position: 'MCM' },
      { name: 'Pierre Woodenski',     position: 'MCM' },
      { name: 'Jeanricner Bellegarde',position: 'MCM' },
      { name: 'Louicius Deedson',     position: 'ATA' },
      { name: 'Ruben Providence',     position: 'ATA' },
      { name: 'Josué Casimir',        position: 'ATA' },
      { name: 'Derrick Etienne',      position: 'ATA' },
      { name: 'Wilson Isidor',        position: 'ATA' },
      { name: 'Duckens Nazon',        position: 'ATA' },
      { name: 'Frantzdy Pierrot',     position: 'ATA' },
      { name: 'Yassin Fortune',       position: 'ATA' },
      { name: 'Lenny Joseph',         position: 'ATA' },
    ],
  },
  {
    name: 'República da Coreia', shieldEmoji: '🇰🇷',
    players: [
      { name: 'Song Bumkeun',   position: 'GK'  },
      { name: 'Jo Hyeonwoo',    position: 'GK'  },
      { name: 'Kim Seung-gyu',  position: 'GK'  },
      { name: 'Lee Kihyuk',     position: 'LAT' },
      { name: 'Kim Moonhwan',   position: 'LAT' },
      { name: 'Cho Yumin',      position: 'LAT' },
      { name: 'Jens Castrop',   position: 'ZAG' },
      { name: 'Lee Hanbeom',    position: 'ZAG' },
      { name: 'Park Jinseob',   position: 'ZAG' },
      { name: 'Kim Minjae',     position: 'ZAG' },
      { name: 'Lee Taeseok',    position: 'ZAG' },
      { name: 'Seol Youngwoo',  position: 'ZAG' },
      { name: 'Kim Taehyeon',   position: 'ZAG' },
      { name: 'Lee Donggyeong', position: 'MCM' },
      { name: 'Hwang Heechan',  position: 'MCM' },
      { name: 'Yang Hyunjun',   position: 'MCM' },
      { name: 'Hwang Inbeom',   position: 'MCM' },
      { name: 'Lee Jaesung',    position: 'MCM' },
      { name: 'Kim Jingyu',     position: 'MCM' },
      { name: 'Eom Jisung',     position: 'MCM' },
      { name: 'Bae Junho',      position: 'MCM' },
      { name: 'Lee Kangin',     position: 'MCM' },
      { name: 'Paik Seungho',   position: 'MCM' },
      { name: 'Cho Guesung',    position: 'ATA' },
      { name: 'Son Heungmin',   position: 'ATA' },
      { name: 'Oh Hyeongyu',    position: 'ATA' },
    ],
  },
  {
    name: 'Áustria', shieldEmoji: '🇦🇹',
    players: [
      { name: 'Alexander Schelager',    position: 'GK'  },
      { name: 'Florian Wiegele',        position: 'GK'  },
      { name: 'Patrick Pentz',          position: 'GK'  },
      { name: 'Alexander Prass',        position: 'LAT' },
      { name: 'Philipp Mwene',          position: 'LAT' },
      { name: 'Stefan Posch',           position: 'LAT' },
      { name: 'David Affengruber',      position: 'ZAG' },
      { name: 'David Alaba',            position: 'ZAG' },
      { name: 'Kevin Danso',            position: 'ZAG' },
      { name: 'Marco Fiedl',            position: 'ZAG' },
      { name: 'Michael Svoboda',        position: 'ZAG' },
      { name: 'Philipp Lienhart',       position: 'ZAG' },
      { name: 'Alessandro Schöpf',      position: 'MCM' },
      { name: 'Christoph Baumgartner',  position: 'MCM' },
      { name: 'Carney Chukwuenmeka',    position: 'MCM' },
      { name: 'Florian Grillitsch',     position: 'MCM' },
      { name: 'Konrad Laimer',          position: 'MCM' },
      { name: 'Romano Schmid',          position: 'MCM' },
      { name: 'Nicolas Seiwald',        position: 'MCM' },
      { name: 'Paul Wanner',            position: 'MCM' },
      { name: 'Patrick Wimmer',         position: 'MCM' },
      { name: 'Marko Arnautovic',       position: 'ATA' },
      { name: 'Michael Gregoritsch',    position: 'ATA' },
      { name: 'Sasa Kalajdzic',         position: 'ATA' },
    ],
  },
  {
    name: 'Cabo Verde', shieldEmoji: '🇨🇻',
    players: [
      { name: 'Josimar Dias',         position: 'GK'  },
      { name: 'Márcio da Rosa',        position: 'GK'  },
      { name: 'Carlos Santos',         position: 'GK'  },
      { name: 'Steven Moreira',        position: 'LAT' },
      { name: 'Kelvin Pires',          position: 'LAT' },
      { name: 'Wagner Pina',           position: 'LAT' },
      { name: 'João Paulo Fernandes',  position: 'ZAG' },
      { name: 'Sidny Cabral',          position: 'ZAG' },
      { name: 'Logan Costa',           position: 'ZAG' },
      { name: 'Roberto Lopes',         position: 'ZAG' },
      { name: 'Ianique Tavares',       position: 'ZAG' },
      { name: 'Edilson Borges',        position: 'ZAG' },
      { name: 'Jamiro Monteiro',       position: 'MCM' },
      { name: 'Deroy Duarte',          position: 'MCM' },
      { name: 'Kevin Pina',            position: 'MCM' },
      { name: 'Laros Duarte',          position: 'MCM' },
      { name: 'Telmo Arcanjo',         position: 'MCM' },
      { name: 'Yannick Semedo',        position: 'MCM' },
      { name: 'Garry Rodrigues',       position: 'ATA' },
      { name: 'Jovane Cabral',         position: 'ATA' },
      { name: 'Ryan Mendes',           position: 'ATA' },
      { name: 'Nuno da Costa',         position: 'ATA' },
      { name: 'Dailon Livramento',     position: 'ATA' },
      { name: 'Gilson Benchimol',      position: 'ATA' },
      { name: 'Willy Semedo',          position: 'ATA' },
      { name: 'Hélio Varela',          position: 'ATA' },
    ],
  },
  {
    name: 'Curaçao', shieldEmoji: '🇨🇼',
    players: [
      { name: 'Tyrick Bodak',       position: 'GK'  },
      { name: 'Trevor Doornbusch',  position: 'GK'  },
      { name: 'Eloy Room',          position: 'GK'  },
      { name: 'Joshua Brenet',      position: 'LAT' },
      { name: 'Sherel Floranus',    position: 'LAT' },
      { name: 'Shurandy Sambo',     position: 'LAT' },
      { name: 'Riechedly Bazoer',   position: 'ZAG' },
      { name: 'Roshon van Eijma',   position: 'ZAG' },
      { name: 'Deveron Fonville',   position: 'ZAG' },
      { name: 'Juriën Gaari',       position: 'ZAG' },
      { name: 'Armando Obispo',     position: 'ZAG' },
      { name: 'Juninho Bacuna',     position: 'MCM' },
      { name: 'Leandro Bacuna',     position: 'MCM' },
      { name: 'Livano Comenencia',  position: 'MCM' },
      { name: 'Kevin Felida',       position: 'MCM' },
      { name: "Ar'Jany Martha",     position: 'MCM' },
      { name: 'Tyrese Noslin',      position: 'MCM' },
      { name: 'Godfried Romeratoe', position: 'MCM' },
      { name: 'Jeremy Antonisse',   position: 'ATA' },
      { name: 'Sontje Hansen',      position: 'ATA' },
      { name: 'Tahith Chong',       position: 'ATA' },
      { name: 'Brandley Kuwas',     position: 'ATA' },
      { name: 'Gervane Kastaneer',  position: 'ATA' },
      { name: 'Jürgen Locadia',     position: 'ATA' },
      { name: 'Jearl Margaritha',   position: 'ATA' },
      { name: 'Kenji Gorré',        position: 'ATA' },
    ],
  },
  {
    name: 'Rep. Democrática do Congo', shieldEmoji: '🇨🇩',
    players: [
      { name: 'Lionel Mpasi',       position: 'GK'  },
      { name: 'Thimothy Fayulu',    position: 'GK'  },
      { name: 'Matthieu Epolo',     position: 'GK'  },
      { name: 'Aaron Wan-Bissaka',  position: 'LAT' },
      { name: 'Arthur Masuaku',     position: 'LAT' },
      { name: 'Chancel Mbemba',     position: 'ZAG' },
      { name: 'Alex Tuanzebe',      position: 'ZAG' },
      { name: 'Joris Kayembe',      position: 'ZAG' },
      { name: 'Steve Kapuadi',      position: 'ZAG' },
      { name: 'Rocky Bushiri',      position: 'ZAG' },
      { name: 'Dylan Batubinsika',  position: 'ZAG' },
      { name: 'Gédéon Kalulu',      position: 'ZAG' },
      { name: 'Noah Sadiki',        position: 'MCM' },
      { name: 'Samuel Moutoussamy', position: 'MCM' },
      { name: 'Edo Kayembe',        position: 'MCM' },
      { name: "Ngal'ayel Mukau",    position: 'MCM' },
      { name: 'Charles Pickel',     position: 'MCM' },
      { name: 'Nathanael Mbuku',    position: 'MCM' },
      { name: 'Brian Cipenga',      position: 'MCM' },
      { name: 'Meschack Elia',      position: 'MCM' },
      { name: 'Gaël Kakuta',        position: 'MCM' },
      { name: 'Théo Bongonda',      position: 'ATA' },
      { name: 'Fiston Mayele',      position: 'ATA' },
      { name: 'Cédric Bakambu',     position: 'ATA' },
      { name: 'Simon Banza',        position: 'ATA' },
      { name: 'Yoane Wissa',        position: 'ATA' },
    ],
  },
  {
    name: 'Escócia', shieldEmoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    players: [
      { name: 'Craig Gordon',        position: 'GK'  },
      { name: 'Angus Gunn',          position: 'GK'  },
      { name: 'Liam Kelly',          position: 'GK'  },
      { name: 'Aaron Hickey',        position: 'LAT' },
      { name: 'Nathan Patterson',    position: 'LAT' },
      { name: 'Andy Robertson',      position: 'LAT' },
      { name: 'Kieran Tierney',      position: 'LAT' },
      { name: 'Anthony Ralston',     position: 'LAT' },
      { name: 'Grant Hanley',        position: 'ZAG' },
      { name: 'Jack Hendry',         position: 'ZAG' },
      { name: 'Dom Hyam',            position: 'ZAG' },
      { name: 'Scott McKenna',       position: 'ZAG' },
      { name: 'John Souttar',        position: 'ZAG' },
      { name: 'Ryan Christie',       position: 'MCM' },
      { name: 'Findlay Curtis',      position: 'MCM' },
      { name: 'Lewis Ferguson',      position: 'MCM' },
      { name: 'Ben Gannon-Doak',     position: 'MCM' },
      { name: 'Billy Gilmour',       position: 'MCM' },
      { name: 'John McGinn',         position: 'MCM' },
      { name: 'Kenny McLean',        position: 'MCM' },
      { name: 'Scott McTominay',     position: 'MCM' },
      { name: 'Che Adams',           position: 'ATA' },
      { name: 'Lyndon Dykes',        position: 'ATA' },
      { name: 'George Hirst',        position: 'ATA' },
      { name: 'Lawrence Shankland',  position: 'ATA' },
      { name: 'Ross Stewart',        position: 'ATA' },
    ],
  },
  {
    name: 'Suíça', shieldEmoji: '🇨🇭',
    players: [
      { name: 'Gregor Kobel',       position: 'GK'  },
      { name: 'Yvon Mvogo',         position: 'GK'  },
      { name: 'Marvin Keller',      position: 'GK'  },
      { name: 'Miro Muheim',        position: 'LAT' },
      { name: 'Ricardo Rodriguez',  position: 'LAT' },
      { name: 'Silvan Widmer',      position: 'LAT' },
      { name: 'Luca Jaquez',        position: 'LAT' },
      { name: 'Manuel Akanji',      position: 'ZAG' },
      { name: 'Aurele Amenda',      position: 'ZAG' },
      { name: 'Eray Comert',        position: 'ZAG' },
      { name: 'Nico Elvedi',        position: 'ZAG' },
      { name: 'Michel Aebischer',   position: 'MCM' },
      { name: 'Christian Fassnacht',position: 'MCM' },
      { name: 'Remo Freuler',       position: 'MCM' },
      { name: 'Ardon Jashari',      position: 'MCM' },
      { name: 'Johan Manzambi',     position: 'MCM' },
      { name: 'Fabian Rieder',      position: 'MCM' },
      { name: 'Djibril Sow',        position: 'MCM' },
      { name: 'Ruben Vargas',       position: 'MCM' },
      { name: 'Granit Xhaka',       position: 'MCM' },
      { name: 'Denis Zakaria',      position: 'MCM' },
      { name: 'Zeki Amdouni',       position: 'ATA' },
      { name: 'Breel Embolo',       position: 'ATA' },
      { name: 'Cedric Itten',       position: 'ATA' },
      { name: 'Dan Ndoye',          position: 'ATA' },
      { name: 'Noah Okafor',        position: 'ATA' },
    ],
  },
  {
    name: 'Alemanha', shieldEmoji: '🇩🇪',
    players: [
      { name: 'Manuel Neuer',         position: 'GK'  },
      { name: 'Oliver Baumann',       position: 'GK'  },
      { name: 'Alexander Nubel',      position: 'GK'  },
      { name: 'Joshua Kimmich',       position: 'LAT' },
      { name: 'David Raum',           position: 'LAT' },
      { name: 'Pascal Gross',         position: 'LAT' },
      { name: 'Waldemar Anton',       position: 'ZAG' },
      { name: 'Nathaniel Brown',      position: 'ZAG' },
      { name: 'Felix Nmecha',         position: 'ZAG' },
      { name: 'Aleksandar Pavlovic',  position: 'ZAG' },
      { name: 'Antonio Rudiger',      position: 'ZAG' },
      { name: 'Nico Schlotterbeck',   position: 'ZAG' },
      { name: 'Angelo Stiller',       position: 'ZAG' },
      { name: 'Jonathan Tah',         position: 'ZAG' },
      { name: 'Malick Thiaw',         position: 'ZAG' },
      { name: 'Nadiem Amiri',         position: 'MCM' },
      { name: 'Leon Goretzka',        position: 'MCM' },
      { name: 'Lennart Karl',         position: 'MCM' },
      { name: 'Jamie Leweling',       position: 'MCM' },
      { name: 'Leroy Sané',           position: 'MCM' },
      { name: 'Maximilian Beier',     position: 'MCM' },
      { name: 'Nick Woltemade',       position: 'ATA' },
      { name: 'Florian Wirtz',        position: 'ATA' },
      { name: 'Deniz Undav',          position: 'ATA' },
      { name: 'Jamal Musiala',        position: 'ATA' },
      { name: 'Kai Havertz',          position: 'ATA' },
    ],
  },
  {
    name: 'Noruega', shieldEmoji: '🇳🇴',
    players: [
      { name: 'Egil Selvik',           position: 'GK'  },
      { name: 'Orjan Nyland',          position: 'GK'  },
      { name: 'Sander Tangvik',        position: 'GK'  },
      { name: 'Fredrik Bjorkan',       position: 'LAT' },
      { name: 'Julian Ryerson',        position: 'LAT' },
      { name: 'Henrik Falchener',      position: 'LAT' },
      { name: 'Kristoffer Ajer',       position: 'ZAG' },
      { name: 'Sondre Langas',         position: 'ZAG' },
      { name: 'Torbjorn Heggem',       position: 'ZAG' },
      { name: 'Holmgren Pedersen',     position: 'ZAG' },
      { name: 'Leo Ostigard',          position: 'ZAG' },
      { name: 'David Moller',          position: 'MCM' },
      { name: 'Martin Odegaard',       position: 'MCM' },
      { name: 'Patrick Berg',          position: 'MCM' },
      { name: 'Kristian Thorstvedt',   position: 'MCM' },
      { name: 'Thelo Aasgaard',        position: 'MCM' },
      { name: 'Fredrik Aursnes',       position: 'MCM' },
      { name: 'Sander Berge',          position: 'MCM' },
      { name: 'Morten Thorsby',        position: 'MCM' },
      { name: 'Strand Larsen',         position: 'ATA' },
      { name: 'Oscar Bobb',            position: 'ATA' },
      { name: 'Erling Haaland',        position: 'ATA' },
      { name: 'Andreas Schjelderup',   position: 'ATA' },
      { name: 'Jens Petter Hauge',     position: 'ATA' },
      { name: 'Antonio Nusa',          position: 'ATA' },
      { name: 'Alexander Sorloth',     position: 'ATA' },
    ],
  },
  {
    name: 'Senegal', shieldEmoji: '🇸🇳',
    players: [
      { name: 'Édouard Mendy',       position: 'GK'  },
      { name: 'Mory Diaw',           position: 'GK'  },
      { name: 'Yehvann Diouf',       position: 'GK'  },
      { name: 'Antoine Mendy',       position: 'LAT' },
      { name: 'Moustapha Mbow',      position: 'LAT' },
      { name: 'Ismail Jakobs',       position: 'LAT' },
      { name: 'Ilay Camara',         position: 'LAT' },
      { name: 'Kalidou Koulibaly',   position: 'ZAG' },
      { name: 'El Hadji Malich Diouf',position:'ZAG' },
      { name: 'Mamadou Sarr',        position: 'ZAG' },
      { name: 'Moussa Niakhaté',     position: 'ZAG' },
      { name: 'Abdoulaye Seck',      position: 'ZAG' },
      { name: 'Krépin Diatta',       position: 'MCM' },
      { name: 'Idrissa Gana Gueye',  position: 'MCM' },
      { name: 'Pape Gueye',          position: 'MCM' },
      { name: 'Lamine Camara',       position: 'MCM' },
      { name: 'Habib Diarra',        position: 'MCM' },
      { name: 'Pathé Ciss',          position: 'MCM' },
      { name: 'Pape Matar Sarr',     position: 'MCM' },
      { name: 'Bara Sapoko Ndiaye',  position: 'MCM' },
      { name: 'Sadio Mané',          position: 'ATA' },
      { name: 'Ismaila Sarr',        position: 'ATA' },
      { name: 'Iliman Ndiaye',       position: 'ATA' },
      { name: 'Assane Diao',         position: 'ATA' },
      { name: 'Ibrahim Mbaye',       position: 'ATA' },
      { name: 'Nicolas Jackson',     position: 'ATA' },
      { name: 'Bamba Dieng',         position: 'ATA' },
      { name: 'Chérif Ndiaye',       position: 'ATA' },
    ],
  },
  {
    name: 'Inglaterra', shieldEmoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    players: [
      { name: 'Jordan Pickford',   position: 'GK'  },
      { name: 'Dean Henderson',    position: 'GK'  },
      { name: 'James Trafford',    position: 'GK'  },
      { name: 'Reece James',       position: 'LAT' },
      { name: 'Tino Livramento',   position: 'LAT' },
      { name: 'Djed Spence',       position: 'LAT' },
      { name: "Nico O'Reilly",     position: 'LAT' },
      { name: 'Ezri Konsa',        position: 'ZAG' },
      { name: 'Jarell Quansah',    position: 'ZAG' },
      { name: 'John Stones',       position: 'ZAG' },
      { name: 'Marc Guehi',        position: 'ZAG' },
      { name: 'Dan Burn',          position: 'ZAG' },
      { name: 'Declan Rice',       position: 'MCM' },
      { name: 'Elliot Anderson',   position: 'MCM' },
      { name: 'Kobbie Mainoo',     position: 'MCM' },
      { name: 'Jordan Henderson',  position: 'MCM' },
      { name: 'Morgan Rogers',     position: 'MCM' },
      { name: 'Jude Bellingham',   position: 'MCM' },
      { name: 'Eberechi Eze',      position: 'MCM' },
      { name: 'Harry Kane',        position: 'ATA' },
      { name: 'Ivan Toney',        position: 'ATA' },
      { name: 'Ollie Watkins',     position: 'ATA' },
      { name: 'Bukayo Saka',       position: 'ATA' },
      { name: 'Marcus Rashford',   position: 'ATA' },
      { name: 'Anthony Gordon',    position: 'ATA' },
      { name: 'Noni Madueke',      position: 'ATA' },
    ],
  },
  {
    name: 'Argentina', shieldEmoji: '🇦🇷',
    players: [
      { name: 'Emiliano Martínez',   position: 'GK'  },
      { name: 'Gerónimo Rulli',      position: 'GK'  },
      { name: 'Juan Musso',          position: 'GK'  },
      { name: 'Nahuel Molina',       position: 'LAT' },
      { name: 'Gonzalo Montiel',     position: 'LAT' },
      { name: 'Nicolás Tagliafico',  position: 'LAT' },
      { name: 'Marcos Acuña',        position: 'LAT' },
      { name: 'Cristian Romero',     position: 'ZAG' },
      { name: 'Lisandro Martínez',   position: 'ZAG' },
      { name: 'Nicolás Otamendi',    position: 'ZAG' },
      { name: 'Leonardo Balerdi',    position: 'ZAG' },
      { name: 'Facundo Medina',      position: 'ZAG' },
      { name: 'Rodrigo De Paul',     position: 'MCM' },
      { name: 'Enzo Fernández',      position: 'MCM' },
      { name: 'Alexis Mac Allister', position: 'MCM' },
      { name: 'Leandro Paredes',     position: 'MCM' },
      { name: 'Exequiel Palacios',   position: 'MCM' },
      { name: 'Giovani Lo Celso',    position: 'MCM' },
      { name: 'Franco Mastantuono',  position: 'MCM' },
      { name: 'Claudio Echeverri',   position: 'MCM' },
      { name: 'Lionel Messi',        position: 'ATA' },
      { name: 'Julián Álvarez',      position: 'ATA' },
      { name: 'Lautaro Martínez',    position: 'ATA' },
      { name: 'Alejandro Garnacho',  position: 'ATA' },
      { name: 'Valentín Carboni',    position: 'ATA' },
      { name: 'Nicolás González',    position: 'ATA' },
    ],
  },
  {
    name: 'Uruguai', shieldEmoji: '🇺🇾',
    players: [
      { name: 'Sergio Rochet',          position: 'GK'  },
      { name: 'Santiago Mele',          position: 'GK'  },
      { name: 'Franco Israel',          position: 'GK'  },
      { name: 'Guillermo Varela',       position: 'LAT' },
      { name: 'Nahitan Nández',         position: 'LAT' },
      { name: 'Mathías Olivera',        position: 'LAT' },
      { name: 'Joaquín Piquerez',       position: 'LAT' },
      { name: 'Ronald Araújo',          position: 'ZAG' },
      { name: 'José María Giménez',     position: 'ZAG' },
      { name: 'Sebastián Cáceres',      position: 'ZAG' },
      { name: 'Santiago Bueno',         position: 'ZAG' },
      { name: 'Federico Valverde',      position: 'MCM' },
      { name: 'Manuel Ugarte',          position: 'MCM' },
      { name: 'Rodrigo Bentancur',      position: 'MCM' },
      { name: 'Nicolás De la Cruz',     position: 'MCM' },
      { name: 'Giorgian De Arrascaeta', position: 'MCM' },
      { name: 'Facundo Pellistri',      position: 'MCM' },
      { name: 'Brian Rodríguez',        position: 'MCM' },
      { name: 'Darwin Núñez',           position: 'ATA' },
      { name: 'Maximiliano Araújo',     position: 'ATA' },
      { name: 'Facundo Torres',         position: 'ATA' },
      { name: 'Agustín Canobbio',       position: 'ATA' },
      { name: 'Cristian Olivera',       position: 'ATA' },
      { name: 'Luciano Rodríguez',      position: 'ATA' },
    ],
  },
  {
    name: 'Canadá', shieldEmoji: '🇨🇦',
    players: [
      { name: 'Maxime Crépeau',        position: 'GK'  },
      { name: 'Dayne St. Clair',       position: 'GK'  },
      { name: 'Owen Goodman',          position: 'GK'  },
      { name: 'Alphonso Davies',       position: 'LAT' },
      { name: 'Alistair Johnston',     position: 'LAT' },
      { name: 'Richie Laryea',         position: 'LAT' },
      { name: 'Niko Sigur',            position: 'LAT' },
      { name: 'Moïse Bombito',         position: 'ZAG' },
      { name: 'Derek Cornelius',       position: 'ZAG' },
      { name: 'Luc de Fougerolles',    position: 'ZAG' },
      { name: 'Alfie Jones',           position: 'ZAG' },
      { name: 'Stephen Eustáquio',     position: 'MCM' },
      { name: 'Ismaël Koné',           position: 'MCM' },
      { name: 'Mathieu Choinière',     position: 'MCM' },
      { name: 'Nathan Saliba',         position: 'MCM' },
      { name: 'Jonathan Osorio',       position: 'MCM' },
      { name: 'Jonathan David',        position: 'ATA' },
      { name: 'Cyle Larin',            position: 'ATA' },
      { name: 'Promise David',         position: 'ATA' },
      { name: 'Tani Oluwaseyi',        position: 'ATA' },
      { name: 'Daniel Jebbison',       position: 'ATA' },
      { name: 'Tajon Buchanan',        position: 'ATA' },
      { name: 'Liam Millar',           position: 'ATA' },
      { name: 'Ali Ahmed',             position: 'ATA' },
      { name: 'Marcelo Flores',        position: 'ATA' },
      { name: 'Jacob Shaffelburg',     position: 'ATA' },
    ],
  },
  {
    name: 'Arábia Saudita', shieldEmoji: '🇸🇦',
    players: [
      { name: 'Mohammed Al-Owais',       position: 'GK'  },
      { name: 'Nawaf Al-Aqidi',          position: 'GK'  },
      { name: 'Ahmed Al-Kassar',         position: 'GK'  },
      { name: 'Saud Abdulhamid',         position: 'LAT' },
      { name: 'Ali Majrashi',            position: 'LAT' },
      { name: 'Moteb Al-Harbi',          position: 'LAT' },
      { name: 'Nawaf Boushal',           position: 'LAT' },
      { name: 'Hassan Tambakti',         position: 'ZAG' },
      { name: 'Ali Lajami',              position: 'ZAG' },
      { name: 'Abdulilah Al-Omari',      position: 'ZAG' },
      { name: 'Hassan Kadish',           position: 'ZAG' },
      { name: 'Mohammed Kanoo',          position: 'MCM' },
      { name: 'Nasser Al-Dawsari',       position: 'MCM' },
      { name: 'Abdullah Al-Khaibari',    position: 'MCM' },
      { name: 'Musab Al-Juwair',         position: 'MCM' },
      { name: 'Ziyad Al-Juhani',         position: 'MCM' },
      { name: 'Alaa Al-Haji',            position: 'MCM' },
      { name: 'Mohammed Abu Al-Shamat',  position: 'MCM' },
      { name: 'Salem Al-Dawsari',        position: 'ATA' },
      { name: 'Saleh Al-Shehri',         position: 'ATA' },
      { name: 'Abdullah Al-Hamdan',      position: 'ATA' },
      { name: 'Ayman Yahya',             position: 'ATA' },
      { name: 'Firas Al-Buraikan',       position: 'ATA' },
      { name: 'Khalid Al-Ghannam',       position: 'ATA' },
      { name: 'Sultan Mandash',          position: 'ATA' },
      { name: 'Abdullah Al-Salem',       position: 'ATA' },
    ],
  },
  {
    name: 'Egito', shieldEmoji: '🇪🇬',
    players: [
      { name: 'Mohamed El Shenawy',          position: 'GK'  },
      { name: 'Mostafa Shobeir',             position: 'GK'  },
      { name: 'El Mahdy Soliman',            position: 'GK'  },
      { name: 'Mohamed Hany',                position: 'LAT' },
      { name: 'Ahmed Fatouh',                position: 'LAT' },
      { name: 'Karim Hafez',                 position: 'LAT' },
      { name: 'Tarek Alaa',                  position: 'LAT' },
      { name: 'Mohamed Abdelmonem',          position: 'ZAG' },
      { name: 'Rami Rabia',                  position: 'ZAG' },
      { name: 'Yasser Ibrahim',              position: 'ZAG' },
      { name: 'Hossam Abdelmaguid',          position: 'ZAG' },
      { name: 'Hamdy Fathy',                 position: 'ZAG' },
      { name: 'Marwan Attia',                position: 'MCM' },
      { name: 'Mohanad Lasheen',             position: 'MCM' },
      { name: 'Emam Ashour',                 position: 'MCM' },
      { name: 'Nabil Emad Donga',            position: 'MCM' },
      { name: 'Mahmoud Saber',               position: 'MCM' },
      { name: 'Ahmed Sayed Zizo',            position: 'MCM' },
      { name: 'Mahmoud Hassan Trezeguet',    position: 'MCM' },
      { name: 'Ibrahim Adel',                position: 'MCM' },
      { name: 'Haissem Hassan',              position: 'MCM' },
      { name: 'Mostafa Ziko',                position: 'MCM' },
      { name: 'Mohamed Salah',               position: 'ATA' },
      { name: 'Omar Marmoush',               position: 'ATA' },
      { name: 'Hamza Abdelkarim',            position: 'ATA' },
      { name: 'Aqtay Abdallah',              position: 'ATA' },
    ],
  },
  {
    name: 'Argélia', shieldEmoji: '🇩🇿',
    players: [
      { name: 'Anthony Mandrea',      position: 'GK'  },
      { name: 'Alexandre Oukidja',    position: 'GK'  },
      { name: 'Alexis Guendouz',      position: 'GK'  },
      { name: 'Rayan Aït-Nouri',      position: 'LAT' },
      { name: 'Ramy Bensebaini',      position: 'LAT' },
      { name: 'Kevin Guitoun',        position: 'LAT' },
      { name: 'Mohamed Farsi',        position: 'LAT' },
      { name: 'Aïssa Mandi',          position: 'ZAG' },
      { name: 'Mohamed Amine Tougaï', position: 'ZAG' },
      { name: 'Ahmed Touba',          position: 'ZAG' },
      { name: 'Jaouen Hadjam',        position: 'ZAG' },
      { name: 'Zineddine Belaïd',     position: 'ZAG' },
      { name: 'Ismaël Bennacer',      position: 'MCM' },
      { name: 'Houssem Aouar',        position: 'MCM' },
      { name: 'Ramiz Zerrouki',       position: 'MCM' },
      { name: 'Farès Chaïbi',         position: 'MCM' },
      { name: 'Ibrahim Maza',         position: 'MCM' },
      { name: 'Himad Abdelli',        position: 'MCM' },
      { name: 'Yacine Titraoui',      position: 'MCM' },
      { name: 'Adil Aouchiche',       position: 'MCM' },
      { name: 'Riyad Mahrez',         position: 'ATA' },
      { name: 'Mohamed Amoura',       position: 'ATA' },
      { name: 'Amine Gouiri',         position: 'ATA' },
      { name: 'Anis Hadj Moussa',     position: 'ATA' },
      { name: 'Amine Chiakha',        position: 'ATA' },
      { name: 'Adil Boulbina',        position: 'ATA' },
    ],
  },
  {
    name: 'Austrália', shieldEmoji: '🇦🇺',
    players: [
      { name: 'Mathew Ryan',          position: 'GK'  },
      { name: 'Joe Gauci',            position: 'GK'  },
      { name: 'Paul Izzo',            position: 'GK'  },
      { name: 'Aziz Behich',          position: 'LAT' },
      { name: 'Jordan Bos',           position: 'LAT' },
      { name: 'Lewis Miller',         position: 'LAT' },
      { name: 'Jason Geria',          position: 'LAT' },
      { name: 'Harry Souttar',        position: 'ZAG' },
      { name: 'Alessandro Circati',   position: 'ZAG' },
      { name: 'Cameron Burgess',      position: 'ZAG' },
      { name: 'Kye Rowles',           position: 'ZAG' },
      { name: 'Kai Trewin',           position: 'ZAG' },
      { name: 'Jackson Irvine',       position: 'MCM' },
      { name: "Aiden O'Neill",        position: 'MCM' },
      { name: 'Connor Metcalfe',      position: 'MCM' },
      { name: 'Keanu Baccus',         position: 'MCM' },
      { name: 'Ajdin Hrustic',        position: 'MCM' },
      { name: 'Patrick Yazbek',       position: 'MCM' },
      { name: 'Paul Okon-Engstler',   position: 'MCM' },
      { name: 'Martin Boyle',         position: 'ATA' },
      { name: 'Awer Mabil',           position: 'ATA' },
      { name: 'Nestory Irankunda',    position: 'ATA' },
      { name: 'Kusini Yengi',         position: 'ATA' },
      { name: 'Tete Yengi',           position: 'ATA' },
      { name: 'Mohamed Toure',        position: 'ATA' },
      { name: 'Samuel Silvera',       position: 'ATA' },
      { name: 'Brandon Borrello',     position: 'ATA' },
    ],
  },
  {
    name: 'Catar', shieldEmoji: '🇶🇦',
    players: [
      { name: 'Meshaal Barsham',      position: 'GK'  },
      { name: 'Mahmoud Abunada',      position: 'GK'  },
      { name: 'Salah Zakaria',        position: 'GK'  },
      { name: 'Pedro Miguel',         position: 'LAT' },
      { name: 'Ahmed Fathi',          position: 'LAT' },
      { name: 'Homam Al-Amin',        position: 'LAT' },
      { name: 'Sultan Al-Brake',      position: 'LAT' },
      { name: 'Lucas Mendes',         position: 'ZAG' },
      { name: 'Bassam Al-Rawi',       position: 'ZAG' },
      { name: 'Boualem Khoukhi',      position: 'ZAG' },
      { name: 'Tarek Salman',         position: 'ZAG' },
      { name: 'Jassim Jaber',         position: 'ZAG' },
      { name: 'Assim Madibo',         position: 'MCM' },
      { name: 'Abdulaziz Hatem',      position: 'MCM' },
      { name: 'Mohammed Waad',        position: 'MCM' },
      { name: 'Ahmed Al-Ganehi',      position: 'MCM' },
      { name: 'Ayoub Al-Alawi',       position: 'MCM' },
      { name: 'Tahseen Mohammed',     position: 'MCM' },
      { name: 'Hassan Al-Haydos',     position: 'MCM' },
      { name: 'Youssef Abdurisag',    position: 'MCM' },
      { name: 'Akram Afif',           position: 'ATA' },
      { name: 'Almoez Ali',           position: 'ATA' },
      { name: 'Edmilson Junior',      position: 'ATA' },
      { name: 'Mohammed Muntari',     position: 'ATA' },
      { name: 'Mohammed Al-Mannai',   position: 'ATA' },
      { name: 'Sebastian Soria',      position: 'ATA' },
    ],
  },
  {
    name: 'Equador', shieldEmoji: '🇪🇨',
    players: [
      { name: 'Hernán Galíndez',    position: 'GK'  },
      { name: 'Moisés Ramírez',     position: 'GK'  },
      { name: 'Gonzalo Valle',      position: 'GK'  },
      { name: 'Pervis Estupiñán',   position: 'LAT' },
      { name: 'Angelo Preciado',    position: 'LAT' },
      { name: 'José Hurtado',       position: 'LAT' },
      { name: 'Willian Pacho',      position: 'ZAG' },
      { name: 'Piero Hincapié',     position: 'ZAG' },
      { name: 'Joel Ordóñez',       position: 'ZAG' },
      { name: 'Félix Torres',       position: 'ZAG' },
      { name: 'Robert Arboleda',    position: 'ZAG' },
      { name: 'Moisés Caicedo',     position: 'MCM' },
      { name: 'Alan Franco',        position: 'MCM' },
      { name: 'Kendry Páez',        position: 'MCM' },
      { name: 'Pedro Vite',         position: 'MCM' },
      { name: 'Denil Castillo',     position: 'MCM' },
      { name: 'Jordy Alcívar',      position: 'MCM' },
      { name: 'Yaimar Medina',      position: 'MCM' },
      { name: 'Enner Valencia',     position: 'ATA' },
      { name: 'Gonzalo Plata',      position: 'ATA' },
      { name: 'John Yeboah',        position: 'ATA' },
      { name: 'Alan Minda',         position: 'ATA' },
      { name: 'Kevin Rodríguez',    position: 'ATA' },
      { name: 'Leonardo Campana',   position: 'ATA' },
      { name: 'Nilson Angulo',      position: 'ATA' },
      { name: 'Jeremy Arévalo',     position: 'ATA' },
    ],
  },
  {
    name: 'Gana', shieldEmoji: '🇬🇭',
    players: [
      { name: 'Lawrence Ati-Zigi',        position: 'GK'  },
      { name: 'Benjamin Asare',           position: 'GK'  },
      { name: 'Joseph Anang',             position: 'GK'  },
      { name: 'Baba Abdul Rahman',        position: 'LAT' },
      { name: 'Gideon Mensah',            position: 'LAT' },
      { name: 'Marvin Senaya',            position: 'LAT' },
      { name: 'Alidu Seidu',              position: 'LAT' },
      { name: 'Alexander Djiku',          position: 'ZAG' },
      { name: 'Jerome Opoku',             position: 'ZAG' },
      { name: 'Abdul Mumin',              position: 'ZAG' },
      { name: 'Jonas Adjetey',            position: 'ZAG' },
      { name: 'Kojo Peprah Oppong',       position: 'ZAG' },
      { name: 'Thomas Partey',            position: 'MCM' },
      { name: 'Elisha Owusu',             position: 'MCM' },
      { name: 'Caleb Yirenkyi',           position: 'MCM' },
      { name: 'Kwasi Sibo',               position: 'MCM' },
      { name: 'Augustine Boakye',         position: 'MCM' },
      { name: 'Abdul Fatawu Issahaku',    position: 'MCM' },
      { name: 'Kamaldeen Sulemana',       position: 'MCM' },
      { name: 'Jordan Ayew',              position: 'ATA' },
      { name: 'Antoine Semenyo',          position: 'ATA' },
      { name: 'Iñaki Williams',           position: 'ATA' },
      { name: 'Ernest Nuamah',            position: 'ATA' },
      { name: 'Christopher Bonsu Baah',   position: 'ATA' },
      { name: 'Brandon Thomas-Asante',    position: 'ATA' },
      { name: 'Prince Kwabena Adu',       position: 'ATA' },
    ],
  },
  {
    name: 'Irã', shieldEmoji: '🇮🇷',
    players: [
      { name: 'Alireza Beiranvand',         position: 'GK'  },
      { name: 'Seyed Hossein Hosseini',     position: 'GK'  },
      { name: 'Payam Niazmand',             position: 'GK'  },
      { name: 'Ramin Rezaeian',             position: 'LAT' },
      { name: 'Saleh Hardani',              position: 'LAT' },
      { name: 'Milad Mohammadi',            position: 'LAT' },
      { name: 'Ehsan Hajsafi',              position: 'LAT' },
      { name: 'Hossein Kanaani',            position: 'ZAG' },
      { name: 'Shoja Khalilzadeh',          position: 'ZAG' },
      { name: 'Ali Nemati',                 position: 'ZAG' },
      { name: 'Danial Eiri',                position: 'ZAG' },
      { name: 'Omid Noorafkan',             position: 'MCM' },
      { name: 'Saeid Ezatolahi',            position: 'MCM' },
      { name: 'Roozbeh Cheshmi',            position: 'MCM' },
      { name: 'Mohammad Karimi',            position: 'MCM' },
      { name: 'Mehdi Torabi',               position: 'MCM' },
      { name: 'Alireza Jahanbakhsh',        position: 'MCM' },
      { name: 'Ali Gholizadeh',             position: 'MCM' },
      { name: 'Mohammad Mohebi',            position: 'MCM' },
      { name: 'Mehdi Ghayedi',              position: 'MCM' },
      { name: 'Mehdi Taremi',               position: 'ATA' },
      { name: 'Allahyar Sayyadmanesh',      position: 'ATA' },
      { name: 'Amirhossein Hosseinzadeh',   position: 'ATA' },
      { name: 'Reza Asadi',                 position: 'ATA' },
      { name: 'Dennis Eckert Ayensa',       position: 'ATA' },
      { name: 'Mehdi Abdi',                 position: 'ATA' },
    ],
  },
  {
    name: 'Iraque', shieldEmoji: '🇮🇶',
    players: [
      { name: 'Jalal Hassan',         position: 'GK'  },
      { name: 'Ahmed Basil',          position: 'GK'  },
      { name: 'Fahad Talib',          position: 'GK'  },
      { name: 'Hussein Ali',          position: 'LAT' },
      { name: 'Merchas Doski',        position: 'LAT' },
      { name: 'Mustafa Saadoon',      position: 'LAT' },
      { name: 'Ahmed Yahya',          position: 'LAT' },
      { name: 'Rebin Sulaka',         position: 'ZAG' },
      { name: 'Frans Putros',         position: 'ZAG' },
      { name: 'Dario Naamo',          position: 'ZAG' },
      { name: 'Akam Hashem',          position: 'ZAG' },
      { name: 'Zaid Tahseen',         position: 'ZAG' },
      { name: 'Zidane Iqbal',         position: 'MCM' },
      { name: 'Amir Al-Ammari',       position: 'MCM' },
      { name: 'Youssef Amyn',         position: 'MCM' },
      { name: 'Ibrahim Bayesh',       position: 'MCM' },
      { name: 'Marko Farji',          position: 'MCM' },
      { name: 'Peter Gwargis',        position: 'MCM' },
      { name: 'Ahmed Qasim',          position: 'MCM' },
      { name: 'Kevin Yakob',          position: 'MCM' },
      { name: 'Hasan Abdulkareem',    position: 'MCM' },
      { name: 'Ali Jassim',           position: 'ATA' },
      { name: 'Aymen Hussein',        position: 'ATA' },
      { name: 'Mohanad Ali',          position: 'ATA' },
      { name: 'Zaid Ismail',          position: 'ATA' },
      { name: 'Karar Nabeel',         position: 'ATA' },
    ],
  },
  {
    name: 'Jordânia', shieldEmoji: '🇯🇴',
    players: [
      { name: 'Yazid Abu Layla',         position: 'GK'  },
      { name: 'Abdullah Al-Fakhouri',    position: 'GK'  },
      { name: 'Noor Bani Attieh',        position: 'GK'  },
      { name: 'Ehsan Haddad',            position: 'LAT' },
      { name: 'Mohammad Abu Al-Nadi',    position: 'LAT' },
      { name: 'Mohannad Abu Taha',       position: 'LAT' },
      { name: 'Ahmad Assaf',             position: 'LAT' },
      { name: 'Abdullah Naseeb',         position: 'ZAG' },
      { name: 'Yazan Al-Arab',           position: 'ZAG' },
      { name: 'Anas Badawi',             position: 'ZAG' },
      { name: 'Hossam Abu Al-Dahab',     position: 'ZAG' },
      { name: 'Saleem Obeid',            position: 'ZAG' },
      { name: 'Nizar Al-Rashdan',        position: 'MCM' },
      { name: 'Noor Al-Rawabdeh',        position: 'MCM' },
      { name: 'Rajaei Ayed',             position: 'MCM' },
      { name: 'Mohammad Al-Daoud',       position: 'MCM' },
      { name: 'Amer Jamous',             position: 'MCM' },
      { name: 'Yousef Qashi',            position: 'MCM' },
      { name: 'Ibrahim Saadeh',          position: 'MCM' },
      { name: 'Mousa Al-Tamari',         position: 'ATA' },
      { name: 'Ali Olwan',               position: 'ATA' },
      { name: 'Mahmoud Al-Mardi',        position: 'ATA' },
      { name: 'Mohammad Abu Zraiq',      position: 'ATA' },
      { name: 'Ibrahim Sabra',           position: 'ATA' },
      { name: 'Ali Azaizeh',             position: 'ATA' },
      { name: 'Odeh Fakhoury',           position: 'ATA' },
    ],
  },
  {
    name: 'Turquia', shieldEmoji: '🇹🇷',
    players: [
      { name: 'Uğurcan Çakır',         position: 'GK'  },
      { name: 'Altay Bayındır',         position: 'GK'  },
      { name: 'Mert Günok',             position: 'GK'  },
      { name: 'Ferdi Kadıoğlu',         position: 'LAT' },
      { name: 'Zeki Çelik',             position: 'LAT' },
      { name: 'Mert Müldür',            position: 'LAT' },
      { name: 'Eren Elmalı',            position: 'LAT' },
      { name: 'Merih Demiral',          position: 'ZAG' },
      { name: 'Çağlar Söyüncü',         position: 'ZAG' },
      { name: 'Abdülkerim Bardakcı',    position: 'ZAG' },
      { name: 'Ozan Kabak',             position: 'ZAG' },
      { name: 'Ahmetcan Kaplan',        position: 'ZAG' },
      { name: 'Hakan Çalhanoğlu',       position: 'MCM' },
      { name: 'Arda Güler',             position: 'MCM' },
      { name: 'Orkun Kökçü',            position: 'MCM' },
      { name: 'İsmail Yüksek',          position: 'MCM' },
      { name: 'Kaan Ayhan',             position: 'MCM' },
      { name: 'Salih Özcan',            position: 'MCM' },
      { name: 'Atakan Karazor',         position: 'MCM' },
      { name: 'Kenan Yıldız',           position: 'ATA' },
      { name: 'Kerem Aktürkoğlu',       position: 'ATA' },
      { name: 'Barış Alper Yılmaz',     position: 'ATA' },
      { name: 'Yunus Akgün',            position: 'ATA' },
      { name: 'Can Uzun',               position: 'ATA' },
      { name: 'Oğuz Aydın',             position: 'ATA' },
      { name: 'İrfan Can Kahveci',      position: 'ATA' },
    ],
  },
  {
    name: 'Uzbequistão', shieldEmoji: '🇺🇿',
    players: [
      { name: 'Utkir Yusupov',              position: 'GK'  },
      { name: 'Abduvohid Nematov',           position: 'GK'  },
      { name: 'Botirali Ergashev',           position: 'GK'  },
      { name: 'Khojiakbar Alijonov',         position: 'LAT' },
      { name: 'Farrukh Sayfiev',             position: 'LAT' },
      { name: 'Sherzod Nasrullaev',          position: 'LAT' },
      { name: 'Ibrokhimkhalil Yuldoshev',    position: 'LAT' },
      { name: 'Abdukodir Khusanov',          position: 'ZAG' },
      { name: 'Rustam Ashurmatov',           position: 'ZAG' },
      { name: 'Umar Eshmurodov',             position: 'ZAG' },
      { name: 'Abdulla Abdullaev',           position: 'ZAG' },
      { name: 'Bekhruz Karimov',             position: 'ZAG' },
      { name: 'Otabek Shukurov',             position: 'MCM' },
      { name: 'Jaloliddin Masharipov',       position: 'MCM' },
      { name: 'Odiljon Hamrobekov',          position: 'MCM' },
      { name: 'Abbosbek Fayzullaev',         position: 'MCM' },
      { name: 'Oston Urunov',                position: 'MCM' },
      { name: 'Akmal Mozgovoy',              position: 'MCM' },
      { name: 'Azizjon Ganiev',              position: 'MCM' },
      { name: 'Eldor Shomurodov',            position: 'ATA' },
      { name: 'Igor Sergeev',                position: 'ATA' },
      { name: 'Sherzod Temirov',             position: 'ATA' },
      { name: 'Dostonbek Khamdamov',         position: 'ATA' },
      { name: 'Khusayin Norchaev',           position: 'ATA' },
      { name: 'Jasurbek Jaloliddinov',       position: 'ATA' },
      { name: 'Ruslanbek Jiyanov',           position: 'ATA' },
    ],
  },
  {
    name: 'México', shieldEmoji: '🇲🇽',
    players: [
      { name: 'Guillermo Ochoa',     position: 'GK'  },
      { name: 'Luis Malagón',        position: 'GK'  },
      { name: 'Raúl Rangel',         position: 'GK'  },
      { name: 'Jorge Sánchez',       position: 'LAT' },
      { name: 'Julián Araujo',       position: 'LAT' },
      { name: 'Jesús Gallardo',      position: 'LAT' },
      { name: 'Bryan González',      position: 'LAT' },
      { name: 'Johan Vásquez',       position: 'ZAG' },
      { name: 'César Montes',        position: 'ZAG' },
      { name: 'Israel Reyes',        position: 'ZAG' },
      { name: 'Ramón Juárez',        position: 'ZAG' },
      { name: 'Víctor Guzmán',       position: 'ZAG' },
      { name: 'Edson Álvarez',       position: 'MCM' },
      { name: 'Luis Chávez',         position: 'MCM' },
      { name: 'Luis Romo',           position: 'MCM' },
      { name: 'Orbelín Pineda',      position: 'MCM' },
      { name: 'Carlos Rodríguez',    position: 'MCM' },
      { name: 'Marcel Ruiz',         position: 'MCM' },
      { name: 'Erik Lira',           position: 'MCM' },
      { name: 'Álvaro Fidalgo',      position: 'MCM' },
      { name: 'Raúl Jiménez',        position: 'ATA' },
      { name: 'Santiago Giménez',    position: 'ATA' },
      { name: 'Julián Quiñones',     position: 'ATA' },
      { name: 'César Huerta',        position: 'ATA' },
      { name: 'Alexis Vega',         position: 'ATA' },
      { name: 'Roberto Alvarado',    position: 'ATA' },
      { name: 'Germán Berterame',    position: 'ATA' },
    ],
  },
  {
    name: 'Paraguai', shieldEmoji: '🇵🇾',
    players: [
      { name: 'Roberto Fernández',       position: 'GK'  },
      { name: 'Orlando Gill',            position: 'GK'  },
      { name: 'Aldo Pérez',              position: 'GK'  },
      { name: 'Juan Cáceres',            position: 'LAT' },
      { name: 'Alan Benítez',            position: 'LAT' },
      { name: 'Blas Riveros',            position: 'LAT' },
      { name: 'Agustín Sández',          position: 'LAT' },
      { name: 'Gustavo Gómez',           position: 'ZAG' },
      { name: 'Junior Alonso',           position: 'ZAG' },
      { name: 'Gustavo Velázquez',       position: 'ZAG' },
      { name: 'Alexis Duarte',           position: 'ZAG' },
      { name: 'Diego Gómez',             position: 'MCM' },
      { name: 'Andrés Cubas',            position: 'MCM' },
      { name: 'Mathías Villasanti',      position: 'MCM' },
      { name: 'Damián Bobadilla',        position: 'MCM' },
      { name: 'Matías Galarza',          position: 'MCM' },
      { name: 'Álvaro Campuzano',        position: 'MCM' },
      { name: 'Kaku Romero Gamarra',     position: 'MCM' },
      { name: 'Alejandro Romero',        position: 'MCM' },
      { name: 'Miguel Almirón',          position: 'ATA' },
      { name: 'Julio Enciso',            position: 'ATA' },
      { name: 'Ramón Sosa',              position: 'ATA' },
      { name: 'Gabriel Ávalos',          position: 'ATA' },
      { name: 'Antonio Sanabria',        position: 'ATA' },
      { name: 'Isidro Pitta',            position: 'ATA' },
      { name: 'Adam Bareiro',            position: 'ATA' },
    ],
  },
];

// ── Main ─────────────────────────────────────────────────────────
async function main() {
  console.log('🔍 Buscando evento Copa do Mundo…');

  const evSnap = await db.collection('events').get();
  const copaEvent = evSnap.docs
    .map((d) => ({ id: d.id, ...d.data() }))
    .find((e) => e.name?.toLowerCase().includes('copa') || e.name?.toLowerCase().includes('copa do mundo'));

  if (!copaEvent) {
    console.error('❌ Evento "Copa do Mundo" não encontrado.');
    console.log('Eventos disponíveis:', evSnap.docs.map((d) => d.data().name).join(', '));
    process.exit(1);
  }

  const eventId = copaEvent.id;
  console.log(`✅ Evento encontrado: "${copaEvent.name}" (${eventId})`);
  console.log(`📋 ${TIMES.length} times, processando…\n`);

  let totalTimes = 0, totalJogadores = 0;

  for (const time of TIMES) {
    const teamRef = await db.collection('teams').add({
      name:        time.name,
      sport:       'futebol',
      eventId,
      shieldEmoji: time.shieldEmoji,
    });

    const teamId = teamRef.id;
    console.log(`🏳️  ${time.name} (${teamId}) — ${time.players.length} jogadores`);

    // Escreve jogadores em lotes de 500 (limite do Firestore)
    const batch = db.batch();
    for (const p of time.players) {
      const pRef = db.collection('players').doc();
      batch.set(pRef, {
        name:     p.name,
        position: p.position,
        teamId,
        sport:    'futebol',
        eventId,
      });
    }
    await batch.commit();

    totalTimes++;
    totalJogadores += time.players.length;
  }

  console.log(`\n✅ Concluído! ${totalTimes} times e ${totalJogadores} jogadores inseridos.`);
  process.exit(0);
}

main().catch((err) => { console.error('❌ Erro:', err.message); process.exit(1); });
